package com.ql.ccs.dataModel.cabin.enumVar

import android.view.View

/**
 * 定义界面id，如果你需要动态添加 控件ID，请在这里添加，然后静态调用，类似于 xml 中的 @+id/ ，这样的写法目的是保证ID不会重复
 */
object MyViewIds {
    //    在 Java 代码中手动为自定义控件添加 ID 时，可以使用 Android 提供的 View.generateViewId() 方法来生成一个唯一的 ID。
    val SettingPageId = View.generateViewId()
    val WorkStatusId = View.generateViewId()
    val FaultDetectionId = View.generateViewId()
    val UnitInfoId = View.generateViewId()
    val UsingHelpId = View.generateViewId()
    val AirOutTempId = View.generateViewId()
    val RecoveryAirTempId = View.generateViewId()
    val OutsideTempId = View.generateViewId()
    val DefrostTempId = View.generateViewId()
    val AreaATempId = View.generateViewId()
    val AreaBTempId = View.generateViewId()
    val AreaCTempId = View.generateViewId()
    val CompExhaustTempId = View.generateViewId()
    val RelativeHumidityId = View.generateViewId()
    val WorkModeId = View.generateViewId()
    val DefrostStatusId = View.generateViewId()
    val SterilizeStatusId = View.generateViewId()
    val BackUpPowerStatusId = View.generateViewId()
    val ECOStatusId = View.generateViewId()
    val RemoteControlStatusId = View.generateViewId()
    val CollisionWarningId = View.generateViewId()
    val CabinDoorId = View.generateViewId()
    val PowerStatusId = View.generateViewId()
    val CompStatusId = View.generateViewId()
    val FrequencyStatusId = View.generateViewId()
    val DCDC1StatusId = View.generateViewId()
    val DCDC2StatusId = View.generateViewId()
    val RunningTimeId = View.generateViewId()
    val ControlVoltageId = View.generateViewId()
    val HighDCVoltageId = View.generateViewId()
    val HighDCCurrentId = View.generateViewId()
    val CompressorSpeedId = View.generateViewId()
    val EvaporatorVoltageId = View.generateViewId()
    val CondenserVoltageId = View.generateViewId()
    val RefrigerantPressureId = View.generateViewId()
    val DefrostIntervalTimeId = View.generateViewId()
    val MaximumRunningTimeId = View.generateViewId()
    val DefrostStopTempId = View.generateViewId()
    val BoxTempCorrectionId = View.generateViewId()
    val EvaporationFanTempModeId = View.generateViewId()
    val NOFaultId = View.generateViewId()
    val CtrlPowerFltId = View.generateViewId()
    val ReAirTempSensorFltId = View.generateViewId()
    val EnvTempSensorFltId = View.generateViewId()
    val EvaporatorOutWindTempSensorFltId = View.generateViewId()
    val DefrostTempSensorFltId = View.generateViewId()
    val RefrigerantHighPresFltId = View.generateViewId()
    val RefrigerantLowPresFltId = View.generateViewId()
    val CompDischargeTempHighFltId = View.generateViewId()
    val InverterFaultId = View.generateViewId()
    val DC_DCFltId = View.generateViewId()
    val HighPresSensorFltId = View.generateViewId()
    val CompExhaustTempSensorFltId = View.generateViewId()
    val AreaATempSensorFltId = View.generateViewId()
    val AreaBTempSensorFltId = View.generateViewId()
    val AreaCTempSensorFltId = View.generateViewId()
    val BoxHumiditySensorFltId = View.generateViewId()
    val MainContactorBlockFltId = View.generateViewId()
    val VehicleVCUNotAllowPowerFaultId = View.generateViewId()
    val TopCtrlDCComFltId = View.generateViewId()
    val TopCtrlInverterComFltId = View.generateViewId()
    val CollisionRadarModuleFltId = View.generateViewId()
    val RemoteManagementModuleRS485IComFltId = View.generateViewId()
    val TopCtrlVehicleVCUComFltId = View.generateViewId()
    val TopCtrlVehicleCCSComFltId = View.generateViewId()
    val TopCtrlPanelComFltId = View.generateViewId()
}